### ISSUE TITLE
Terminal error when get_working_directory

### ISSUE THREAD

**Issue by ZhuFengdaaa** [martyr-deepin/deepin-terminal#47]
I have installed all the below:

```
sudo apt-get install build-essential git qemu-system-x86 vim-gnome gdb cgdb eclipse-cdt make diffutils exuberant-ctags tmux openssh-server cscope meld qgit gitg gcc-multilib gcc-multilib g++-multilib
```

when I excute

```
make debug
```

I face this error

```
TerminalWrapper.get_working_directory got error: [Errno 2] 没有那个文件或目录: '/proc/28075/cwd'
```

**Comment by fasheng** [comment]
Well, if you want experience the last deepin-terminal simply, please ignore the `Makefile`, and just install `deepin-ui` and run the following commands:

```
git checkout release/1.0
python2 src/main.py 
```

For the advanced features like `text searching`, please use the patched `deepin-vte` instead of `vte`.

Here is the install files for Archlinux, hope it helps:
https://github.com/felixonmars/archlinux-community/tree/master/deepin-terminal/trunk

Enjoy. :)

**Comment by manateelazycat** [comment]
deepin terminal 2.0 has fixed this problem, thanks for report!
